### ISSUE TITLE
Can you give a citation to the paper you are addressing in the notebook? Thanks!

### ISSUE THREAD

**Issue by keremw** [JonathanShor/DoubletDetection#55] opened 2018-01-25 08:23 UTC

**Comment by JonathanShor** [comment] 2018-01-25 15:45
To which paper are you referring?

Perhaps this line? "We invite you to read the paper in the github repo to see our results after running on a dataset of two very different cell lines."
If so, its available in the docs folder. It was only published here.

**Comment by JonathanShor** [comment] 2018-03-06 16:15
Haha yes, we used their theme by design, as an exercise.
We are working on actually submitting for publication soon, and will replace the current PDF with that more robust paper once its available.

**Comment by adamgayoso** [comment] 2018-04-09 04:39
Closing this issue as #69 discuss in the works bioarxiv submission

**Closed** 2018-04-09 04:40 UTC
